### PR TITLE
Merge password reset feature to main branch

### PR DESCRIPTION
**Pull request by vio3500**
reset password feature completed

### CODE REVIEW

**Review by kroscedu — APPROVED** [review]
Wait to be modified.

**Review by Hikariks — APPROVED** [review]
赠一周

**Review by wwzzhhrr — APPROVED** [review]
👌

**Review by RayWu-1 — APPROVED** [review]
approve

**Comment by vio3500** [comment]
# 曾奕洲
main-qimg-5d39adb2cbce8f34bb4b24d07da46fa2-lq

**Pull request merged**
